### ISSUE TITLE
大哥，一大推报错啊

### ISSUE THREAD

**Issue by ghost** [blueberryCoder/LiveStream#2]

**Comment by blueberryCoder** [comment]
是不是环境没配好呢？

**Comment by montotone** [comment]
相机权限请求加一下

**Comment by montotone** [comment]
publisher的

**Comment by zhangpeibisha** [comment]
大神，你好，我运行你的库时，报错
PathClassLoader[DexPathList[[zip file "/data/local/tmp/scrcpy-server.jar"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]] couldn't find "libpublish.so"
这是为啥呀

**Comment by blueberryCoder** [comment]
已经重新更改了下，使用源码进行了编译。
