### ISSUE TITLE
问一下

### ISSUE THREAD

**Issue by zzhhz** [blueberryCoder/LiveStream#5]
楼主AndroidPublisher里面的那个rtmp/lib/armeabi/librtmp.so这个so库是怎么得到的呢？是别人写好的，还是自己写的？有源码文件吗？能编译出来arm64-v8a，x86_64这样的适配so库吗

**Comment by blueberryCoder** [comment]
这个库是开源的，要适配 arm64 ,x86的话，你需要重新编译。

这是我之前编译armeabi 的过程:http://blog.csdn.net/a992036795/article/details/54377892

**Comment by zzhhz** [comment]
这个库应该上那个网站去下载？能发一下链接么？谢谢了

**Comment by blueberryCoder** [comment]
http://rtmpdump.mplayerhq.hu/

**Comment by ligoofing** [comment]
你好，你开源的c++的代码是不是和提供的sdk里的不一样，gradle配置sdk里可以正常推流到服务器，配置为代码编译，不用jcenter就不能推流到服务器。能开源更新下sdk里c++代码吗

**Comment by zzhhz** [comment]
这个你自己可以编译吧，下载最新的源码，然后编译成你的so文件，你自己也可以修改源码，前提是Java中调用的方法要匹配
