### ISSUE TITLE
能开源更新下sdk里c++代码吗

### ISSUE THREAD

**Issue by ligoofing** [blueberryCoder/LiveStream#9]
你好，你开源的c++的代码是不是和提供的sdk里的不一样，gradle配置sdk里可以正常推流到服务器，配置为代码编译，不用jcenter就不能推流到服务器。能开源更新下sdk里c++代码吗

**Comment by blueberryCoder** [comment]
代码我全部提交了的。

**Comment by ligoofing** [comment]
但是我使用下面配置 ，不可以推流到服务器（youtube直播）    
compile project(':rtmplive')
使用下面配置，可以推流到服务器（youtube直播）    
compile 'com.blueberry:rtmplive:0.1.0'

**Comment by q46321** [comment]
直接 compile project(':rtmplive') 编译有问题，附上log

In file included from /Users/michael/Android/github/LiveStream-master/AndroidPublisher/rtmplive/src/main/cpp/Rtmp.cpp:5:
  /Users/michael/Android/github/LiveStream-master/AndroidPublisher/rtmplive/src/main/cpp/rtmp.h:17:10: warning: non-portable path to file '"Rtmp.h"'; specified path differs in case from file name on disk [-Wnonportable-include-path]
  #include "rtmp.h"
           ^~~~~~~~
           "Rtmp.h"
  /Users/michael/Android/github/LiveStream-master/AndroidPublisher/rtmplive/src/main/cpp/Rtmp.cpp:35:41: error: use of undeclared identifier 'malloc'
      RTMPPacket *packet = (RTMPPacket *) malloc(RTMP_HEAD_SIZE + 1024);
                                          ^
  /Users/michael/Android/github/LiveStream-master/AndroidPublisher/rtmplive/src/main/cpp/Rtmp.cpp:84:5: error: use of undeclared identifier 'free'
      free(packet);
      ^
  /Users/michael/Android/github/LiveStream-master/AndroidPublisher/rtmplive/src/main/cpp/Rtmp.cpp:97:13: warning: expression result unused [-Wunused-value]
          len - 3;
          ~~~ ^ ~
  /Users/michael/Android/github/LiveStream-master/AndroidPublisher/rtmplive/src/main/cpp/Rtmp.cpp:102:41: error: use of undeclared identifier 'malloc'
      RTMPPacket *packet = (RTMPPacket *) malloc(RTMP_HEAD_SIZE + len + 9);
                                          ^
  /Users/michael/Android/github/LiveStream-master/AndroidPublisher/rtmplive/src/main/cpp/Rtmp.cpp:141:5: error: use of undeclared identifier 'free'
      free(packet);
      ^
  /Users/michael/Android/github/LiveStream-master/AndroidPublisher/rtmplive/src/main/cpp/Rtmp.cpp:150:29: error: use of undeclared identifier 'malloc'
      packet = (RTMPPacket *) malloc(RTMP_HEAD_SIZE + len + 2);
                              ^
  /Users/michael/Android/github/LiveStream-master/AndroidPublisher/rtmplive/src/main/cpp/Rtmp.cpp:171:5: error: use of undeclared identifier 'free'
      free(packet);
      ^
  /Users/michael/Android/github/LiveStream-master/AndroidPublisher/rtmplive/src/main/cpp/Rtmp.cpp:182:33: error: use of undeclared identifier 'malloc'
          packet = (RTMPPacket *) malloc(RTMP_HEAD_SIZE + len + 2);
                                  ^
  /Users/michael/Android/github/LiveStream-master/AndroidPublisher/rtmplive/src/main/cpp/Rtmp.cpp:203:9: error: use of undeclared identifier 'free'
          free(packet);
          ^
  2 warnings and 8 errors generated.
  In file included from /Users/michael/Android/github/LiveStream-master/AndroidPublisher/rtmplive/src/main/cpp/publish_jni.cpp:3:
  /Users/michael/Android/github/LiveStream-master/AndroidPublisher/rtmplive/src/main/cpp/rtmp.h:17:10: warning: non-portable path to file '"Rtmp.h"'; specified path differs in case from file name on disk [-Wnonportable-include-path]
  #include "rtmp.h"
           ^~~~~~~~
           "Rtmp.h"
  1 warning generated.
  ninja: build stopped: subcommand failed.
